name: {{name.snakeCase()}}
description: "{{description}}"
version: 1.0.0
publish_to: 'none'


environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  serinus: ^{{serinus_version}}

dev_dependencies:
  serinus_lint: ^0.1.1
  
